### ISSUE TITLE
What license?

### ISSUE THREAD

**Issue by j2l** [icheer/web-spreadsheet#1]
Hi, 
Great to see this svelte project. Congrats
What is the license?

**Comment by icheer** [comment]
> Hi, Great to see this svelte project. Congrats What is the license?

Hi there,
Glad to hear that you like it.
The license is MIT, and I've uploaded it to the repository just now.

BTW, I found that it's just a toy since I began to use HandsonTable.
This web component will create EVERY dom to render a spreadsheet, so it has poor performance when the row count > 1k...
but if the row count is limited, that's OK. 😃

**Comment by j2l** [comment]
Thank you for your reply and hint about HandsonTable!
